# Generated by Django 5.0 on 2024-02-15 04:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UID', models.CharField(max_length=10)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('profile_img', models.ImageField(upload_to='../profileImages/')),
            ],
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('templateId', models.CharField(max_length=10)),
                ('templateName', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('templateZip', models.FileField(upload_to='')),
                ('totaldownloads', models.IntegerField()),
                ('UID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profileApp.users')),
            ],
        ),
        migrations.CreateModel(
            name='AppLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('U', 'upload'), ('D', 'download'), ('del', 'delete'), ('new', 'new')], max_length=50)),
                ('TID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profileApp.template')),
                ('UID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profileApp.users')),
            ],
        ),
    ]
