# Generated by Django 4.2.10 on 2024-03-02 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='profile_img',
            field=models.ImageField(upload_to='static/'),
        ),
    ]
