# Generated by Django 4.2.10 on 2024-02-15 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profileApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='template',
            name='UID',
        ),
        migrations.DeleteModel(
            name='AppLogs',
        ),
        migrations.DeleteModel(
            name='Template',
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
