# Generated by Django 4.2.10 on 2024-03-30 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='profile_img',
            field=models.ImageField(blank=True, null=True, upload_to='static/'),
        ),
    ]
