# Generated by Django 4.2.10 on 2024-02-15 05:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('UID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('profile_img', models.ImageField(upload_to='../profileImages/')),
            ],
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('templateId', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('templateName', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('templateZip', models.FileField(upload_to='')),
                ('totaldownloads', models.IntegerField()),
                ('UID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='templateData.users')),
            ],
        ),
        migrations.CreateModel(
            name='AppLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(blank=True, choices=[('upload', 'upload'), ('download', 'download'), ('delete', 'delete'), ('new', 'new'), ('default', 'default')], default='def', max_length=10)),
                ('TID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='templateData.template')),
                ('UID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='templateData.users')),
            ],
        ),
    ]
