# Generated by Django 4.2.10 on 2024-02-28 13:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('templateId', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('templateName', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('templateZip', models.FileField(upload_to='')),
                ('totaldownloads', models.IntegerField()),
                ('UID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AppLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(blank=True, choices=[('upload', 'upload'), ('download', 'download'), ('delete', 'delete'), ('new', 'new'), ('default', 'default')], default='default', max_length=10)),
                ('TID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='templateData.template')),
                ('UID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
