# Generated by Django 4.2.10 on 2024-03-27 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templateData', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applogs',
            name='transaction_type',
            field=models.CharField(blank=True, choices=[('upload', 'upload'), ('download', 'download'), ('delete', 'delete'), ('new', 'new'), ('update', 'update'), ('default', 'default')], default='default', max_length=10),
        ),
    ]
