# Generated by Django 4.2.10 on 2024-03-27 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('templateData', '0002_alter_applogs_transaction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applogs',
            name='TID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='templateData.template'),
        ),
    ]
