# Generated by Django 4.2.10 on 2024-03-30 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templateData', '0003_alter_applogs_tid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='templateId',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
    ]
